import fs from "node:fs/promises";
import path from "node:path";
import ExcelJS from "exceljs";

export type VarianceWorkbookLine = {
  requestor: string;
  approvedBy: string;
  date: string;
  fromFund: string;
  fromFundDescription: string;
  fromOrg: string;
  fromOrgDescription: string;
  fromAccount: string;
  fromAccountDescription: string;
  fromAmountMonth: number;
  fromMonthStart?: string;
  toFund: string;
  toFundDescription: string;
  toOrg: string;
  toOrgDescription: string;
  toAccount: string;
  toAccountDescription: string;
  toAmountMonth: number;
  toMonthStart?: string;
  narrative: string;
};

export const VARIANCE_TEMPLATE_BUNDLED_PATH = "public/templates/variance-template.xlsx";
const TEMPLATE_PATHS = [path.join(process.cwd(), VARIANCE_TEMPLATE_BUNDLED_PATH)];
const TEMPLATE_SHEET_NAME = "Template";
const INSTRUCTIONS_SHEET_NAME = "Instructions";
const TEMPLATE_LOAD_ERROR = "Variance template file is missing or could not be loaded. Please contact an administrator.";

const SIENA_TEMPLATE_MAPPING = {
  requestor: "B4",
  approvedBy: "B5",
  date: "B6",
  firstBlockHeaderRow: 8,
  blockHeight: 6,
  removeOffset: 1,
  moveOffset: 2,
  narrativeOffset: 3,
  sourceBlockTemplateStart: 8,
  sourceBlockTemplateEnd: 13,
  narrativeMergeStartColumn: 6,
  narrativeMergeEndColumn: 20,
  totalColumn: 20,
  lineColumns: {
    fund: 1,
    fundDescription: 2,
    org: 3,
    orgDescription: 4,
    account: 6,
    accountDescription: 7
  },
  monthColumns: {
    "06": 8,
    "07": 9,
    "08": 10,
    "09": 11,
    "10": 12,
    "11": 13,
    "12": 14,
    "01": 15,
    "02": 16,
    "03": 17,
    "04": 18,
    "05": 19
  }
} as const;

function cloneStyle(style: Partial<ExcelJS.Style>): Partial<ExcelJS.Style> {
  return JSON.parse(JSON.stringify(style ?? {})) as Partial<ExcelJS.Style>;
}

function monthColumn(monthStart: string | undefined): number {
  const month = monthStart?.slice(5, 7);
  if (month && month in SIENA_TEMPLATE_MAPPING.monthColumns) {
    return SIENA_TEMPLATE_MAPPING.monthColumns[month as keyof typeof SIENA_TEMPLATE_MAPPING.monthColumns];
  }
  return SIENA_TEMPLATE_MAPPING.totalColumn;
}

function logTemplateLoad(details: Record<string, unknown>): void {
  console.info("[variance-workbook] template load", details);
}

async function loadTemplateWorkbook(): Promise<ExcelJS.Workbook> {
  const workbook = new ExcelJS.Workbook();
  for (const templatePath of TEMPLATE_PATHS) {
    const exists = await fs
      .access(templatePath)
      .then(() => true)
      .catch(() => false);
    logTemplateLoad({ resolvedTemplatePath: templatePath, exists });
    if (!exists) continue;

    try {
      await workbook.xlsx.readFile(templatePath);
      logTemplateLoad({
        resolvedTemplatePath: templatePath,
        usedFallback: false,
        sheetNames: workbook.worksheets.map((sheet) => sheet.name)
      });
      return workbook;
    } catch (error) {
      console.error("[variance-workbook] template load failed", {
        resolvedTemplatePath: templatePath,
        error: error instanceof Error ? error.message : String(error)
      });
    }
  }

  if (process.env.NODE_ENV !== "production") {
    console.warn("[variance-workbook] using local development fallback workbook; real Siena template was not loaded.");
    const instructions = workbook.addWorksheet(INSTRUCTIONS_SHEET_NAME);
    instructions.getCell("A1").value = "Variance workbook generated by Theatre Budget App.";
    const template = workbook.addWorksheet(TEMPLATE_SHEET_NAME);
    template.getCell("A1").value = "Variance fallback workbook";
    logTemplateLoad({ usedFallback: true, sheetNames: workbook.worksheets.map((sheet) => sheet.name) });
    return workbook;
  }

  throw new Error(TEMPLATE_LOAD_ERROR);
}

function ensureTemplateSheet(workbook: ExcelJS.Workbook): ExcelJS.Worksheet {
  const sheet = workbook.getWorksheet(TEMPLATE_SHEET_NAME);
  if (!sheet) throw new Error(TEMPLATE_LOAD_ERROR);
  return sheet;
}

function clearBlock(sheet: ExcelJS.Worksheet, blockStartRow: number): void {
  const removeRow = blockStartRow + SIENA_TEMPLATE_MAPPING.removeOffset;
  const moveRow = blockStartRow + SIENA_TEMPLATE_MAPPING.moveOffset;
  const narrativeRow = blockStartRow + SIENA_TEMPLATE_MAPPING.narrativeOffset;
  const clearColumns = [
    ...Object.values(SIENA_TEMPLATE_MAPPING.lineColumns),
    ...Object.values(SIENA_TEMPLATE_MAPPING.monthColumns),
    SIENA_TEMPLATE_MAPPING.totalColumn
  ];

  for (const rowNumber of [removeRow, moveRow]) {
    for (const columnNumber of clearColumns) {
      sheet.getCell(rowNumber, columnNumber).value = null;
    }
  }
  sheet.getCell(narrativeRow, SIENA_TEMPLATE_MAPPING.narrativeMergeStartColumn).value = null;
}

function copyTemplateBlockIfNeeded(sheet: ExcelJS.Worksheet, blockStartRow: number): void {
  if (blockStartRow <= sheet.rowCount) return;
  const templateStart = SIENA_TEMPLATE_MAPPING.sourceBlockTemplateStart;
  const templateEnd = SIENA_TEMPLATE_MAPPING.sourceBlockTemplateEnd;
  for (let offset = 0; offset <= templateEnd - templateStart; offset += 1) {
    const sourceRow = sheet.getRow(templateStart + offset);
    const targetRow = sheet.getRow(blockStartRow + offset);
    targetRow.height = sourceRow.height;
    for (let columnNumber = 1; columnNumber <= SIENA_TEMPLATE_MAPPING.totalColumn; columnNumber += 1) {
      const sourceCell = sourceRow.getCell(columnNumber);
      const targetCell = targetRow.getCell(columnNumber);
      targetCell.value = sourceCell.value;
      targetCell.style = cloneStyle(sourceCell.style);
    }
    targetRow.commit();
  }

  const narrativeRow = blockStartRow + SIENA_TEMPLATE_MAPPING.narrativeOffset;
  const narrativeRange = `F${narrativeRow}:T${narrativeRow}`;
  if (!sheet.getCell(narrativeRow, SIENA_TEMPLATE_MAPPING.narrativeMergeStartColumn).isMerged) {
    sheet.mergeCells(narrativeRange);
  }
}

function writeBudgetSide(
  sheet: ExcelJS.Worksheet,
  rowNumber: number,
  params: {
    fund: string;
    fundDescription: string;
    org: string;
    orgDescription: string;
    account: string;
    accountDescription: string;
    amount: number;
    monthStart?: string;
  }
): void {
  const { lineColumns, totalColumn } = SIENA_TEMPLATE_MAPPING;
  sheet.getCell(rowNumber, lineColumns.fund).value = params.fund;
  sheet.getCell(rowNumber, lineColumns.fundDescription).value = params.fundDescription;
  sheet.getCell(rowNumber, lineColumns.org).value = params.org;
  sheet.getCell(rowNumber, lineColumns.orgDescription).value = params.orgDescription;
  sheet.getCell(rowNumber, lineColumns.account).value = params.account;
  sheet.getCell(rowNumber, lineColumns.accountDescription).value = params.accountDescription;
  sheet.getCell(rowNumber, monthColumn(params.monthStart)).value = params.amount;
  sheet.getCell(rowNumber, totalColumn).value = params.amount;
}

function writeLine(sheet: ExcelJS.Worksheet, line: VarianceWorkbookLine, index: number): void {
  const blockStartRow = SIENA_TEMPLATE_MAPPING.firstBlockHeaderRow + index * SIENA_TEMPLATE_MAPPING.blockHeight;
  copyTemplateBlockIfNeeded(sheet, blockStartRow);
  clearBlock(sheet, blockStartRow);

  const removeRow = blockStartRow + SIENA_TEMPLATE_MAPPING.removeOffset;
  const moveRow = blockStartRow + SIENA_TEMPLATE_MAPPING.moveOffset;
  const narrativeRow = blockStartRow + SIENA_TEMPLATE_MAPPING.narrativeOffset;

  writeBudgetSide(sheet, removeRow, {
    fund: line.fromFund,
    fundDescription: line.fromFundDescription,
    org: line.fromOrg,
    orgDescription: line.fromOrgDescription,
    account: line.fromAccount,
    accountDescription: line.fromAccountDescription,
    amount: line.fromAmountMonth,
    monthStart: line.fromMonthStart
  });
  writeBudgetSide(sheet, moveRow, {
    fund: line.toFund,
    fundDescription: line.toFundDescription,
    org: line.toOrg,
    orgDescription: line.toOrgDescription,
    account: line.toAccount,
    accountDescription: line.toAccountDescription,
    amount: line.toAmountMonth,
    monthStart: line.toMonthStart
  });
  sheet.getCell(narrativeRow, SIENA_TEMPLATE_MAPPING.narrativeMergeStartColumn).value = line.narrative;
}

function writeHeader(sheet: ExcelJS.Worksheet, line: VarianceWorkbookLine | undefined): void {
  if (!line) return;
  sheet.getCell(SIENA_TEMPLATE_MAPPING.requestor).value = line.requestor;
  sheet.getCell(SIENA_TEMPLATE_MAPPING.approvedBy).value = line.approvedBy;
  sheet.getCell(SIENA_TEMPLATE_MAPPING.date).value = line.date ? new Date(`${line.date}T00:00:00`) : null;
}

function clearUnusedBlocks(sheet: ExcelJS.Worksheet, usedLineCount: number): void {
  const blockCount = Math.ceil(Math.max(sheet.rowCount - SIENA_TEMPLATE_MAPPING.firstBlockHeaderRow, 0) / SIENA_TEMPLATE_MAPPING.blockHeight);
  for (let index = usedLineCount; index < blockCount; index += 1) {
    const blockStartRow = SIENA_TEMPLATE_MAPPING.firstBlockHeaderRow + index * SIENA_TEMPLATE_MAPPING.blockHeight;
    clearBlock(sheet, blockStartRow);
  }
}

function buildFallbackWorkbook(lines: VarianceWorkbookLine[]): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  const instructions = workbook.addWorksheet(INSTRUCTIONS_SHEET_NAME);
  instructions.getCell("A1").value = "Variance workbook generated by Theatre Budget App.";
  const template = workbook.addWorksheet(TEMPLATE_SHEET_NAME);
  template.addRow(["Requestor", "Approved By", "Date", "From Org", "From Account", "From Amount", "To Org", "To Account", "To Amount", "Narrative"]);
  for (const line of lines) {
    template.addRow([
      line.requestor,
      line.approvedBy,
      line.date,
      line.fromOrg,
      line.fromAccount,
      line.fromAmountMonth,
      line.toOrg,
      line.toAccount,
      line.toAmountMonth,
      line.narrative
    ]);
  }
  return workbook;
}

export async function generateVarianceWorkbook(lines: VarianceWorkbookLine[]): Promise<Buffer> {
  const workbook = await loadTemplateWorkbook();
  const sheet = ensureTemplateSheet(workbook);
  if (!sheet.getCell("A4").value && process.env.NODE_ENV !== "production") {
    const fallbackWorkbook = buildFallbackWorkbook(lines);
    const fallbackBuffer = await fallbackWorkbook.xlsx.writeBuffer();
    return Buffer.from(fallbackBuffer);
  }

  writeHeader(sheet, lines[0]);
  lines.forEach((line, index) => writeLine(sheet, line, index));
  clearUnusedBlocks(sheet, lines.length);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
