import fs from "node:fs/promises";
import path from "node:path";
import ExcelJS from "exceljs";

export type VarianceWorkbookLine = {
  requestor: string;
  approvedBy: string;
  date: string;
  fromFund: string;
  fromFundDescription: string;
  fromOrg: string;
  fromOrgDescription: string;
  fromAccount: string;
  fromAccountDescription: string;
  fromAmountMonth: number;
  toFund: string;
  toFundDescription: string;
  toOrg: string;
  toOrgDescription: string;
  toAccount: string;
  toAccountDescription: string;
  toAmountMonth: number;
  narrative: string;
};

export const VARIANCE_TEMPLATE_BUNDLED_PATH = "public/templates/variance-template.xlsx";
const TEMPLATE_PATHS = [
  path.join(process.cwd(), VARIANCE_TEMPLATE_BUNDLED_PATH),
  path.join(process.cwd(), "source-sheets", "variance-template.xlsx")
];
const TEMPLATE_SHEET_NAME = "Template";
const INSTRUCTIONS_SHEET_NAME = "Instructions";
const FIRST_DATA_ROW = 2;

const columns = [
  { header: "Requestor", key: "requestor", width: 22 },
  { header: "Approved By", key: "approvedBy", width: 22 },
  { header: "Date", key: "date", width: 14 },
  { header: "From Fund", key: "fromFund", width: 14 },
  { header: "From Fund Description", key: "fromFundDescription", width: 24 },
  { header: "From Org", key: "fromOrg", width: 14 },
  { header: "From Org Description", key: "fromOrgDescription", width: 24 },
  { header: "From Account", key: "fromAccount", width: 14 },
  { header: "From Account Description", key: "fromAccountDescription", width: 28 },
  { header: "From Amount/Month", key: "fromAmountMonth", width: 18 },
  { header: "To Fund", key: "toFund", width: 14 },
  { header: "To Fund Description", key: "toFundDescription", width: 24 },
  { header: "To Org", key: "toOrg", width: 14 },
  { header: "To Org Description", key: "toOrgDescription", width: 24 },
  { header: "To Account", key: "toAccount", width: 14 },
  { header: "To Account Description", key: "toAccountDescription", width: 28 },
  { header: "To Amount/Month", key: "toAmountMonth", width: 18 },
  { header: "Narrative", key: "narrative", width: 42 }
] as const;

async function loadTemplateWorkbook(): Promise<ExcelJS.Workbook> {
  const workbook = new ExcelJS.Workbook();
  for (const templatePath of TEMPLATE_PATHS) {
    try {
      await fs.access(templatePath);
      await workbook.xlsx.readFile(templatePath);
      return workbook;
    } catch {
      // Try the next known bundled/dev path.
    }
  }

  const instructions = workbook.addWorksheet(INSTRUCTIONS_SHEET_NAME);
  instructions.getCell("A1").value = "Variance workbook generated by Theatre Budget App.";
  const template = workbook.addWorksheet(TEMPLATE_SHEET_NAME);
  template.columns = columns.map((column) => ({ header: column.header, key: column.key, width: column.width }));
  template.getRow(1).font = { bold: true };
  template.views = [{ state: "frozen", ySplit: 1 }];
  return workbook;
}

function ensureTemplateSheet(workbook: ExcelJS.Workbook): ExcelJS.Worksheet {
  let sheet = workbook.getWorksheet(TEMPLATE_SHEET_NAME);
  if (!sheet) {
    sheet = workbook.addWorksheet(TEMPLATE_SHEET_NAME);
  }
  for (let index = 0; index < columns.length; index += 1) {
    const columnNumber = index + 1;
    sheet.getCell(1, columnNumber).value = columns[index].header;
    sheet.getColumn(columnNumber).width = columns[index].width;
  }
  sheet.getRow(1).font = { bold: true };
  return sheet;
}

function clearTemplateData(sheet: ExcelJS.Worksheet): void {
  const lastRow = Math.max(sheet.rowCount, FIRST_DATA_ROW);
  for (let rowNumber = FIRST_DATA_ROW; rowNumber <= lastRow; rowNumber += 1) {
    const row = sheet.getRow(rowNumber);
    row.values = [];
    row.commit();
  }
}

export async function generateVarianceWorkbook(lines: VarianceWorkbookLine[]): Promise<Buffer> {
  const workbook = await loadTemplateWorkbook();
  const sheet = ensureTemplateSheet(workbook);
  clearTemplateData(sheet);

  lines.forEach((line, index) => {
    const row = sheet.getRow(FIRST_DATA_ROW + index);
    const values = [
      line.requestor,
      line.approvedBy,
      line.date,
      line.fromFund,
      line.fromFundDescription,
      line.fromOrg,
      line.fromOrgDescription,
      line.fromAccount,
      line.fromAccountDescription,
      line.fromAmountMonth,
      line.toFund,
      line.toFundDescription,
      line.toOrg,
      line.toOrgDescription,
      line.toAccount,
      line.toAccountDescription,
      line.toAmountMonth,
      line.narrative
    ];
    values.forEach((value, valueIndex) => {
      row.getCell(valueIndex + 1).value = value;
    });
    row.getCell(10).numFmt = "$#,##0.00";
    row.getCell(17).numFmt = "$#,##0.00";
    row.commit();
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
